### PR TITLE
Updating default plot behavior

### PR DESCRIPTION
**Pull request by mortonjt**
This updates default behavior for addressing missing samples.

Now missing samples will be dropped rather than throwing an error.

Include any questions for reviewers, screenshots, sample outputs, etc.
@ElDeveloper @thermokarst  - what do you think of this?

### CODE REVIEW

**Comment by ElDeveloper** [comment]
I think I would opt to expose this argument via the command line. I believe it makes sense to stop and alert the user when they have data for which no metadata exists (something that I think is an anti-pattern).

Minor correction: missing samples are not dropped, they are instead marked as containing no metadata whatsoever.

**Comment by ebolyen** [comment]
Other plugins will typically force metadata (or other annotation-like artifacts) to be a superset of the artifact in question. This prevents simple mistakes like the metadata having a typo in the Sample ID where the artifact doesn't (or vice-versa). 

Intersection as a default would mask that situation, however a flag like @ElDeveloper suggests would be very convenient and prevent accidental masking.

**Comment by mortonjt** [comment]
I can do it next week

**Comment by mortonjt** [comment]
Closing in favor of #71

**Pull request closed without merging**
