### PR TITLE
Change website from HTTPS -> HTTP

### PR DESCRIPTION
**Pull request by ElDeveloper**

### CODE REVIEW

**Comment by jairideout** [comment]
👍 

In the future, can you create feature branches on your fork of q2-emperor and submit PRs from your fork? That's how we're PRing things in the qiime2 org -- it avoids having unnecessary branches created on the upstream repo, and Travis-CI gets confused when testing upstream branches (e.g. see the failure above for `travis-ci/push`, it's grabbing an outdated .travis.yml somehow).

**Comment by ElDeveloper** [comment]
@jairideout haha for sure, I forgot to fork when I transferred ownership to the QIIME2 organization. 👌

**Comment by jairideout** [comment]
Thanks @ElDeveloper! Can I delete the existing branches on this repo or are there any that you'd like saved (i.e. WIP branches that haven't been merged yet)?

**Comment by ElDeveloper** [comment]
@jairideout you can't, because I just deleted them! 😶

**Comment by jairideout** [comment]
Thanks @ElDeveloper!!

**Pull request merged**
