### PR TITLE
BLD: Update to latest beta

### PR DESCRIPTION
**Pull request by ElDeveloper**

### CODE REVIEW

**Comment by jairideout** [comment]
👍 

Are there any user-facing changes worth noting in our release announcement/changelog? If there are I'd be happy to add some text to the release notes.

**Comment by ElDeveloper** [comment]
Yes, there are a couple, the most notable:

- Axes are no longer labeled using numbers (0 (x %), 1 (y %), 2 (z %)).
- Axes visibility is now changed using dropdown menus instead of the scree plot.
- The context menu is now displayed when right clicking on the plot area, and no longer needs users to hold shift while right clicking.
- Adds the ability to create high resolution PNGs using the context menu.
- Add the ability to "recenter the camera" using the context menu.
- Fixes a problem with axes labels disappearing or being blurred for certain metrics.
- Fixes a bug where "certain floating" point numbers would fail to be mapped to a continuous colorscheme. 
- Metadata dropdowns no longer select an option by default, this is changed for all the tabs. As a consequence of this change, the color of samples is set to red by default.
- Improve startup time (mostly noticeable in large datasets).

---------------------

There's a lot going on here, let me know if I can help clarify or expand something 👍

**Comment by ElDeveloper** [comment]
Thanks @jairideout!

**Comment by jairideout** [comment]
Thanks for the release notes @ElDeveloper! Do you have a changelog or release announcement for Emperor 1.0.0beta7 that we could link to in addition to these highlights? No problem if not, just wanted to include it if there's one out there already.

**Comment by ElDeveloper** [comment]
No changelog or release announcement beyond the release page by GitHub:
https://github.com/biocore/emperor/releases/tag/1.0.0-beta.7
Thanks!

**Comment by jairideout** [comment]
OK thanks!

**Comment by ElDeveloper** [comment]
Thanks!!! 👏🏽

**Pull request merged**
