### PR TITLE
Update to the latest EMPeror version 🐧

### PR DESCRIPTION
**Pull request by ElDeveloper**
Bumps dependency version to 1.0.3, depends on the following PR being merged and creating a new release:

biocore/emperor#799

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Just waiting on the conda-forge build now: https://github.com/conda-forge/emperor-feedstock/pull/31

**Comment by ElDeveloper** [comment]
This should be good to be merged.

**Comment by thermokarst** [comment]
@ElDeveloper - did anything change in the conda recipe, dependency-wise? The CI runs aren't able to resolve a satisfactory conda env - we're seeing some incompatible packages in here. Do you have any ideas?

**Comment by ElDeveloper** [comment]
@thermokarst Not that I am aware of. I think conda-forge's base libraries (probably glib) may have changed recently and it's causing trouble with the rest of the dependencies. Is there any way we could install with pip instead of conda? If so the emperor release is pip installable.

**Review by thermokarst — APPROVED** [review]

**Comment by ElDeveloper** [comment]
Thanks so much for figuring this one out @lizgehret and @thermokarst!

**Pull request merged**
