### PR TITLE
new: python 3.8

### PR DESCRIPTION
**Pull request by thermokarst**
Co-authored-by: Keegan Evans <45274931+Keegan-Evans@users.noreply.github.com>

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Thanks @thermokarst

**Comment by thermokarst** [comment]
Oh thanks @ElDeveloper - this actually isn't ready for primetime just yet though

**Comment by ElDeveloper** [comment]
🔥 my bad!

**Comment by thermokarst** [comment]
Not your fault - I should've put a "do not merge" tag on it. I was going to handle all of the py38 changes a few hrs ago, but a github outage slowed my plans down a bit. More soon!

**Pull request merged**
