### PR TITLE
REL: Update to beta16

### PR DESCRIPTION
**Pull request by ElDeveloper**
Merge this before #60

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Thanks! I've noticed that the macOS builds are much faster now. Woot
woot for quick releases.

**Comment by thermokarst** [comment]
@ElDeveloper, it looks like tests are failing on busywork right now: https://busywork.qiime2.org/teams/main/pipelines/master-distribution/jobs/unit-test-q2-emperor/builds/28

Can you take a look at that when you get a chance? Looks like we probably just need to update some tests in this plugin. 🤙

**Comment by ElDeveloper** [comment]
@thermokarst, this was probably bad practice on my end but I lumped those changes in with #60, would have been much cleaner to put the changes in this branch. I can split those out if needed or we can just wait for #60 to be merged, your call.

**Comment by thermokarst** [comment]
Ah, my bad, I should've put two-and-two together (3?). Addressing in #60 sounds good to me! One of us will review soon!

**Comment by ElDeveloper** [comment]
Excellent, thanks 🤙🏽

**Pull request merged**
